demo_avodha_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='myapp'
urlpatterns = [
    path('',views.demo,name='demo'),
    path('shop/<int:shop_id>',views.detail,name='detail'),
    path('add/',views.add_product,name='add_product'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

demo_avodha_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from demo_avodha_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo_avodha_app.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

demo_avodha_app/models.py
from django.db import models

# Create your models here.
class shop(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    img=models.ImageField(upload_to='picture')
    price=models.IntegerField()

demo_avodha_app/forms.py
from django import forms

from .models import shop

class ModelForm(forms.ModelForm):
    class Meta:
        model=shop
        fields=['name','desc','img','price']

demo_avodha_app/views.py
from .forms import ModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import shop
# Create your views here.
def demo(request):
    product=shop.objects.all()
    return render(request,"home.html",{'products':product})

def detail(request,shop_id):
    product1=shop.objects.get(id=shop_id)
    return render(request,'detail.html',{'product':product1})
def add_product(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc= request.POST.get('desc')
        price= request.POST.get('price')
        img= request.FILES['img']
        s=shop(name=name,desc=desc,img=img,price=price)
        s.save()
        print("product saved")
    return render(request,"add_product.html")
def update(request,id):
    obj=shop.objects.get(id=id)
    form=ModelForm(request.POST or None,request.FILES,instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'obj':obj})
def delete(request,id):
    if request.method=="POST":
      obj=shop.objects.get(id=id)
      obj.delete()
      return redirect('/')
    return render(request,"delete.html",{'obj':id})

templates/add_product.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="product name"><br>
   <input type="text" name="desc" placeholder="product description"><br>
   <input type="file" name="img" placeholder="product images"><br>
   <input type="text" name="price" placeholder="product price"><br>
   <input type="submit"  value="ADD">
</form>
{% endblock %}

templates/base.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
<!--   <img src="{{i.img.url}}" alt="" style="width:300px;height:300px>-->
 online shopping center
  </a>
</nav>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete this item?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">


         <div class="col-md-4">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{product.img.url}}" alt="Card image cap" style="width:250px;height:250px;">
  <div class="card-body">
    <h5 class="card-title">{{product.name}}</h5>
    <p class="card-text">{{product.desc}}</p>
    price$ {{product.price}}<br>
    <a class="btn btn-warning"href="{% url 'myapp:update' product.id %}">UPDATE</a>
<a class="btn btn-danger"href="{% url 'myapp:delete' product.id %}">DELETE</a><br>
  </div>
</div>
   </div>

    </div>
    </div>


{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update">
</form>

templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">

{% for i in products %}
         <div class="col-md-4">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" style="width:250px;height:250px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'myapp:detail' i.id %}" class="btn btn-primary">Go Detail</a>
  </div>
</div>
   </div>
        {% endfor %}
    </div>
    </div>
<!--<img src="{{i.img.url}}" alt="" style="height:200px;width:200px;">-->


{% endblock %}